### Success

POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "Yooo here is a note",
    "important": false
}

### Content too short

POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "Yo",
    "important": false
}

###

POST https://muddy-sound-7810.fly.dev/api/notes
Content-Type: application/json

{
    "content": "VS Code REST client is also a good tool",
    "important": false
}
