GET http://localhost:3001/api/notes

###

//Tests
GET http://localhost:3001/api/notes/5c41c90e84d891c15dfa3431 

###
GET http://localhost:3001/api/notes/"someendpoint"

###

GET http://localhost:3001/api/notes/63d80662b89a5bb162a6a9e1


###

GET https://muddy-sound-7810.fly.dev/api/notes
