
GET http://localhost:3001/api/persons

###

GET http://localhost:3001/api/persons/2


###

GET http://localhost:3001/api/persons/63a210ab7216fd034bbb2de8

###

GET http://localhost:3001/api/persons/"someIncorrectEndpoint"


###

GET https://summer-firefly-2330.fly.dev/api/persons

###

GET https://summer-firefly-2330.fly.dev/api/persons/2
